spring:
  datasource:
    username: root
    password: Coding_@21
    url: jdbc:mysql://localhost:3306/SpringBootRest
    driver-class-name: com.mysql.cj.jdbc.Driver

# data jpa spec

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
